name: Deploy to DigitalOcean

on:
  push:
    branches:
      - master  # O la rama que uses para el despliegue

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.DO_SSH_PRIVATE_KEY }}
        
    - name: Clear existing files in the target folder
      run: |
        ssh -o StrictHostKeyChecking=no root@64.227.110.203 "rm -rf /root/Actions*"
        
    - name: Copy docker-compose to server
      run: |
        ssh -o StrictHostKeyChecking=no root@64.227.110.203 "mkdir -p /root/Actions"  # Ruta en el servidor
        scp -o StrictHostKeyChecking=no docker-compose.yaml root@64.227.110.203:/root/Actions/docker-compose.yaml
        scp -o StrictHostKeyChecking=no -r backend root@64.227.110.203:/root/Actions/backend  # Copia todo el backend
        scp -o StrictHostKeyChecking=no -r frontend root@64.227.110.203:/root/Actions/frontend  # Copia todo el frontend

    - name: Deploy app with Docker Compose
      run: |
        ssh -o StrictHostKeyChecking=no root@64.227.110.203 "cd /root/Actions && docker compose down && docker compose pull && docker compose up -d --build"
