name: Deploy to DigitalOcean

on:
  push:
    branches:
      - master  # O la rama que uses para el despliegue

jobs:
  deploy:
    runs-on: ubuntu 24.10

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.DO_SSH_PRIVATE_KEY }}

    - name: Copy docker-compose to server
      run: |
        ssh -o StrictHostKeyChecking=no root@64.227.110.203 "mkdir -p /var/www/pipBoy"  # Ruta en el servidor
        scp -o StrictHostKeyChecking=no docker-compose.yaml root@64.227.110.203:/var/www/docker-compose.yaml
        scp -o StrictHostKeyChecking=no backend/.env root@64.227.110.203:/var/www/backend/.env  # Si tienes archivos .env específicos
        scp -o StrictHostKeyChecking=no -r backend root@64.227.110.203:/var/www/pipBoy/backend  # Copia todo el backend
        scp -o StrictHostKeyChecking=no -r frontend root@64.227.110.203:/var/www/pipBoy/frontend  # Copia todo el frontend

    - name: Deploy app with Docker Compose
      run: |
        ssh -o StrictHostKeyChecking=no root@64.227.110.203 "cd /var/www/pipBoy && docker-compose down && docker-compose pull && docker-compose up -d --build"
